src/Entity/Contacts.php
<?php

namespace App\Entity;

use App\Repository\ContactsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactsRepository::class)
 */
class Contacts
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $adressEmail;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $codePostal;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdressEmail(): ?string
    {
        return $this->adressEmail;
    }

    public function setAdressEmail(string $adressEmail): self
    {
        $this->adressEmail = $adressEmail;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(string $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }
}

src/Entity/Facture.php
<?php

namespace App\Entity;

use App\Repository\FactureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FactureRepository::class)
 */
class Facture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_emission_facture;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $pourcentage_tva;

    /**
     * @ORM\Column(type="decimal", precision=7, scale=2)
     */
    private $montant_ttc_facture;

    /**
     * @ORM\Column(type="boolean")
     */
    private $facture_acquitee;

    /**
     * @ORM\ManyToOne(targetEntity=Abonnement::class, inversedBy="factures", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $abonnement;

    /**
     * @ORM\OneToMany(targetEntity=Paiement::class, mappedBy="facture")
     */
    private $paiements;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, nullable=true)
     */
    private $montantHT;

    /**
     * @ORM\Column(type="string", length=255, nullable="true")
     */
    private $reference;

    public function __construct()
    {
        $this->paiements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEmissionFacture(): ?\DateTimeInterface
    {
        return $this->date_emission_facture;
    }

    public function setDateEmissionFacture(\DateTimeInterface $date_emission_facture): self
    {
        $this->date_emission_facture = $date_emission_facture;

        return $this;
    }

    public function getPourcentageTva(): ?string
    {
        return $this->pourcentage_tva;
    }

    public function setPourcentageTva(string $pourcentage_tva): self
    {
        $this->pourcentage_tva = $pourcentage_tva;

        return $this;
    }

    public function getMontantTtcFacture(): ?string
    {
        return $this->montant_ttc_facture;
    }

    public function setMontantTtcFacture(string $montant_ttc_facture): self
    {
        $this->montant_ttc_facture = $montant_ttc_facture;

        return $this;
    }

    public function getFactureAcquitee(): ?bool
    {
        return $this->facture_acquitee;
    }

    public function setFactureAcquitee(bool $facture_acquitee): self
    {
        $this->facture_acquitee = $facture_acquitee;

        return $this;
    }

    public function getAbonnement(): ?Abonnement
    {
        return $this->abonnement;
    }

    public function setAbonnement(?Abonnement $abonnement): self
    {
        $this->abonnement = $abonnement;

        return $this;
    }

    /**
     * @return Collection|Paiement[]
     */
    public function getPaiements(): Collection
    {
        return $this->paiements;
    }

    public function addPaiement(Paiement $paiement): self
    {
        if (!$this->paiements->contains($paiement)) {
            $this->paiements[] = $paiement;
            $paiement->setFacture($this);
        }

        return $this;
    }

    public function removePaiement(Paiement $paiement): self
    {
        if ($this->paiements->removeElement($paiement)) {
            // set the owning side to null (unless already changed)
            if ($paiement->getFacture() === $this) {
                $paiement->setFacture(null);
            }
        }

        return $this;
    }

    public function getMontantHT(): ?string
    {
        return $this->montantHT;
    }

    public function setMontantHT(?string $montantHT): self
    {
        $this->montantHT = $montantHT;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }
}

templates/billing/billing.html.twig
<div a>
    <h1>Facture FEM</h1>
    <div c>
        <span>Nom</span><span>{{ client.nom }}</span>
        <span>Prénom</span><span>{{ client.prenom }}</span>
        <span>Montant HT</span><span>{{ facture.montantHT }} €</span>
        <span>TVA</span><span>20%</span>
        <span>Montant TTC</span><span>{{ facture.montantTtcFacture }} €</span>
        <span>Etat de la facture</span><span>{{ facture.factureAcquitee ? 'facture acquitée':'facture non acquitée '}}</span>
    </div>
</div>
<style>
    div[a]{
    width: 500px;
    margin: auto;
    max-width: 95vw;
    padding: 1em 2em;
    background: #1c9fd922;
    }

    [a]h1{
    text-align: center;
    color: #203c76;
    }

    [c]{
    background: white;
    border: 1px dashed black;
    padding: 1em;
    font-family: monospace;
    display: grid;
    grid-template-columns: max-content auto;
    column-gap: .5em;
    row-gap: .8em;
    }

    [a] [c] span{
    position: relative;
    }

    [a] [c] span:nth-child(2n){
    font-weight: 800;
    text-align: right;
    }

    [a] [c] span:nth-child(2n+1)::after{
    content:":";
    position: absolute;
    right: 0; top: 50%;
    transform: translate(100%, -50%);
    }

    [a] [c] span:nth-child(2n+1){
    padding-right: 1em;
    }
</style>

templates/billing/billingEmailTemplate.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Facture FEM</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <style>
            .contentcontainer{
                font-family: Montserrat;
            }
        </style>
    </head>
    <body>
        <div class="contentcontainer">
            <div style="text-align:center; margin-top:39px; margin-bottom:39px;">
                <img src="https://femcreditconso.fr/images/icon/favicon.png" alt="">
            </div>

            <h2 style="text-align:center;">Votre facture abonnement FEM</h2>

            <p style="text-align:center;">Veuillez voir en pièce-jointe la facture relative à l'abonnement !!!!</p>
        </div>
    </body>
</html>

templates/billing/billing_prototype_1.html copy.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Facture FEM</title>
        <style>
            div[a]{
            width: 500px;
            margin: auto;
            max-width: 95vw;
            padding: 1em 2em;
            /* background: #1c9fd922; */
            border: 1px dotted black;
            font-family: monospace!important;
            text-align: left;
            }
            h1{
            text-align: center;
            color: #203c76;
            }

            [c]{
            background: white;
            border: 1px dashed black;
            padding: 1em;
            font-family: monospace;
            display: grid;
            grid-template-columns: max-content auto;
            column-gap: .5em;
            row-gap: .8em;
            }

            [b]{
                /* /* display: grid;
                grid-template-columns: auto auto; 
                display: flex; */
                column-gap: 2em;
                flex-wrap: wrap;
            }
            [f]{
                position: relative;
                color: black;
            }
            [f], [r] {
                margin: .5em 0;
                flex-basis: 50%;
            }
        </style>
    </head>
    <body>
        <div style="text-align:center; margin-top: 50px; margin-bottom: 50px;">
            <img src={{imagePath}} alt="" style="width:auto; height:auto;">
        </div>
        <h1 style="text-align:center; color: #1c9fd9; font-family: sans-serif">Facture FEM</h1>
        <div a>
            <div b>
                <p f>Nom : {{ client.nom }}</p>
                
                <p f>Prenom : {{ client.prenom }}</p>
                
                <p f>Montant HT : {{ facture.montantHT }}</p>
                
                <p f>TVA : {{ facture.pourcentageTva }}</p>
                
                <p f>Montant TTC : {{ facture.montantTtcFacture }}</p>
                
                <p f>Etat de la facture : {{ facture.factureAcquitee ? 'facture acquitée':'facture non acquitée' }}</p>
            </div>
        </div>
        <p style="font-family: sans-serif; width: 500px; margin: 2em auto">
            Merci d'avoir choisi nos services !
        </p>
    </body>
</html>

templates/billing/billing_prototype_1.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Facture FEM</title>
        <style>
            .spacer{
                width: 200px;
            }
            #fac-content{
                border-collapse: collapse;
                width: 100%;
                margin-top: 2em;
            }
            #fac-content td, #fac-content th{
                border: 1px solid black;
            }
            #fac-content td{
                font-family: monospace;
            }
            [r]{
                text-align: right;
            }
            #table-head{
                width: 100%;
            }
            [m]{
                margin: 2em 0;
            }
            #details{
                border-collapse: collapse;
                margin-top: 2em;
            }
            #details td{
                border: 1px solid black;
            }
            [o]{
                font-weight: 800;
            }
            [l]{
                font-family: monospace;
            }
            #client-det{
                margin-top: 3em;
            }
        </style>
    </head>
    <body>
        <table id="table-head">
            <tbody>
                <tr>
                    <td>
                        <img src={{imagePath}} alt="" style="width:200px; height:auto;">
                    </td>
                    <td t>
                        Facture n°: {{ facture.id }}<br/>
                        Date : {{ facture.dateEmissionFacture|date('d-m-Y') }}<br/>
                        Client n°: {{ client ? client.user.id : "" }}<br/>
                    </td>
                </tr>
                <tr m>
                    <td>
                        Finance et Moi<br/>
                        15, avenue d'Angers<br/>
                        79300 BRESSUIRE <br/>
                        Siren: 402 205 686
                    </td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        <table id="client-det">
            <tr>
                <td o="">Nom de l'entreprise </td>
                <td>:</td>
                <td l="">{{client ? client.nomEntreprise : "Nom par défaut"}}</td>
            </tr>
            <tr>
                <td o="">Adresse</td>
                <td>:</td>
                <td l="">{{ client ? client.address : "Addresse par défaut" }}</td>{# To change later when the server part ready #}
            </tr>
            
            <tr>
                <td o="">Code postal</td>
                <td>:</td>
                <td l="">{{ client ? client.postalCode : "Code postal par défaut" }}</td>{# To change later when the server part ready #}
            </tr>

            <tr>
                <td o="">Ville</td>
                <td>:</td>
                <td l="">{{ client ? client.town : "Ville par défaut" }}</td>{# To change later when the server part ready #}
            </tr>
        </table>
        <table id="fac-content">
            <thead>
                <tr>
                    <th>Ref</th>
                    <th>Type d'abonnement</th>
                    <th>Montant HT</th>
                    <th>TVA</th>
                    <th>Montant TTC</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        {{ client ? client.abonnement.typeAbonnement.reference ~ '-' ~ client.user.id : "Essai facture" }}-{{facture.dateEmissionFacture|date('d-m-Y') }}
                    </td>
                    <td>
                        {{ client ? client.abonnement.typeAbonnement.label : "Label par défaut"}}
                    </td>
                    <td r>
                        {{ facture.montantHT }}€
                    </td>
                    <td r>
                        {{ facture.pourcentageTva }}%
                    </td>
                    <td r>
                        {{ facture.montantTtcFacture }}€
                    </td>
                </tr>
            </tbody>
        </table>
        <table id="details">
            <tbody>
                <tr>
                    <td o>Etat de la facture</td>
                    <td l>
                        {{ facture.factureAcquitee ? 'acquitée':'non acquitée' }}
                    </td>
                </tr>
                <tr>
                    <td o>Mode de paiement</td>
                    <td l>
                        Carte Bancaire
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>

templates/billing/billing_sous_compte_prototype_1.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Facture FEM</title>
        <style>
            .spacer{
                width: 200px;
            }
            #fac-content{
                border-collapse: collapse;
                width: 100%;
                margin-top: 2em;
            }
            #fac-content td, #fac-content th{
                border: 1px solid black;
            }
            #fac-content td{
                font-family: monospace;
            }
            [r]{
                text-align: right;
            }
            #table-head{
                width: 100%;
            }
            [m]{
                margin: 2em 0;
            }
            #details{
                border-collapse: collapse;
                margin-top: 2em;
            }
            #details td{
                border: 1px solid black;
            }
            [o]{
                font-weight: 800;
            }
            [l]{
                font-family: monospace;
            }
            #client-det{
                margin-top: 3em;
            }
        </style>
    </head>
    <body>
        <table id="table-head">
            <tbody>
                <tr>
                    <td>
                        <img src={{imagePath}} alt="" style="width:200px; height:auto;">
                    </td>
                    <td t>
                        Facture n°: {{ facture.id }}<br/>
                        Date : {{ facture.dateEmissionFacture|date('d-m-Y') }}<br/>
                        Client n°: {{ client.user.id }}<br/>
                    </td>
                </tr>
                <tr m>
                    <td>
                        Finance et Moi<br/>
                        15, avenue d'Angers<br/>
                        79300 BRESSUIRE <br/>
                        Siren: 402 205 686
                    </td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        <table id="client-det">
            <tr>
                <td o=""> Nom de l'entreprise </td>
                <td>:</td>
                <td l=""> {{ client.client.nomEntreprise }}</td>
            </tr>
            <tr>
                <td o=""> Addresse </td>
                <td>:</td>
                <td l=""> {{ client.client.address }}</td>
            </tr>
            <tr>
                <td o="">Code Postal </td>
                <td>:</td>
                <td l=""> {{ client.client.postalCode }}</td>
            </tr>
            <tr>
                <td o=""> Ville </td>
                <td>:</td>
                <td l=""> {{ client.client.town }}</td>
            </tr>
            <tr>
                <td o="" style="padding-top:20px;">Nom </td>
                <td style="padding-top:20px;">:</td>
                <td l="" style="padding-top:20px;"> {{ client.nom }}</td>
            </tr>
            <tr>
                <td o="">Prenom </td>
                <td>:</td>
                <td l=""> {{ client.prenom }}</td>
            </tr>
            <tr>
                <td o="">Addresse </td>
                <td>:</td>
                <td l=""> {{ client.addresseEntreprise }}</td>
            </tr>
            <tr>
                <td o="">Code postal</td>
                <td>:</td>
                <td l="">{{ client.codePostal }}</td>{# To change later when the server part ready #}
            </tr>
            <tr>
                <td o="">Ville</td>
                <td>:</td>
                <td l="">{{ client.ville }}</td>{# To change later when the server part ready #}
            </tr>
        </table>
        <table id="fac-content">
            <thead>
                <tr>
                    <th>Ref</th>
                    <th>Type d'abonnement</th>
                    <th>Montant HT</th>
                    <th>TVA</th>
                    <th>Montant TTC</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        {{ client.abonnement.typeAbonnement.reference ~ '-' ~ client.user.id }}-{{facture.dateEmissionFacture|date('d-m-Y') }}
                    </td>
                    <td>
                        {{ client.abonnement.typeAbonnement.label }}
                    </td>
                    <td r>
                        {{ facture.montantHT }}€
                    </td>
                    <td r>
                        {{ facture.pourcentageTva }}%
                    </td>
                    <td r>
                        {{ facture.montantTtcFacture }}€
                    </td>
                </tr>
            </tbody>
        </table>
        <table id="details">
            <tbody>
                <tr>
                    <td o>Etat de la facture</td>
                    <td l>
                        {{ facture.factureAcquitee ? 'acquitée':'non acquitée' }}
                    </td>
                </tr>
                <tr>
                    <td o>Mode de paiement</td>
                    <td l>
                        Carte Bancaire
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>