src/Entity/Abonnement.php
<?php

namespace App\Entity;

use App\Repository\AbonnementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AbonnementRepository::class)
 */
class Abonnement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut_abonnement;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_fin_abonnement;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $actif;

    /**
     * @ORM\Column(type="text")
     */
    private $stripe_subscription_id;

    /**
     * @ORM\Column(type="text")
     */
    private $stripe_cus_id;

    /**
     * @ORM\OneToMany(targetEntity=Facture::class, mappedBy="abonnement", orphanRemoval=true)
     */
    private $factures;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mode;

    /**
     * @ORM\Column(type="boolean")
     */
    private $statut_paiement;

    /**
     * @ORM\OneToOne(targetEntity=Client::class, inversedBy="abonnement", cascade={"persist", "remove"}, fetch="EAGER")
     * @ORM\JoinColumn(nullable=true)
     */
    private $client;

    /**
     * @ORM\OneToOne(targetEntity=SousCompte::class, inversedBy="abonnement", cascade={"persist", "remove"})
     */
    private $sousCompte;

    /**
     * @ORM\ManyToOne(targetEntity=TypeAbonnement::class, inversedBy="abonnements", fetch="EAGER")
     */
    private $typeAbonnement;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $raisonDesabonnement;

    public function __construct()
    {
        $this->factures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebutAbonnement(): ?\DateTimeInterface
    {
        return $this->date_debut_abonnement;
    }

    public function setDateDebutAbonnement(\DateTimeInterface $date_debut_abonnement): self
    {
        $this->date_debut_abonnement = $date_debut_abonnement;

        return $this;
    }

    public function getDateFinAbonnement(): ?\DateTimeInterface
    {
        return $this->date_fin_abonnement;
    }

    public function setDateFinAbonnement(?\DateTimeInterface $date_fin_abonnement): self
    {
        $this->date_fin_abonnement = $date_fin_abonnement;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(?bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getStripeSubscriptionId(): ?string
    {
        return $this->stripe_subscription_id;
    }

    public function setStripeSubscriptionId(string $stripe_subscription_id): self
    {
        $this->stripe_subscription_id = $stripe_subscription_id;

        return $this;
    }

    public function getStripeCusId(): ?string
    {
        return $this->stripe_cus_id;
    }

    public function setStripeCusId(string $stripe_cus_id): self
    {
        $this->stripe_cus_id = $stripe_cus_id;

        return $this;
    }

    /**
     * @return Collection|Facture[]
     */
    public function getFactures(): Collection
    {
        return $this->factures;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->factures->contains($facture)) {
            $this->factures[] = $facture;
            $facture->setAbonnement($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->factures->removeElement($facture)) {
            // set the owning side to null (unless already changed)
            if ($facture->getAbonnement() === $this) {
                $facture->setAbonnement(null);
            }
        }

        return $this;
    }

    public function getMode(): ?string
    {
        return $this->mode;
    }

    public function setMode(string $mode): self
    {
        $this->mode = $mode;

        return $this;
    }

    public function getStatutPaiement(): ?bool
    {
        return $this->statut_paiement;
    }

    public function setStatutPaiement(bool $statut_paiement): self
    {
        $this->statut_paiement = $statut_paiement;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getSousCompte(): ?SousCompte
    {
        return $this->sousCompte;
    }

    public function setSousCompte(?SousCompte $sousCompte): self
    {
        $this->sousCompte = $sousCompte;

        return $this;
    }

    public function getTypeAbonnement(): ?TypeAbonnement
    {
        return $this->typeAbonnement;
    }

    public function setTypeAbonnement(?TypeAbonnement $typeAbonnement): self
    {
        $this->typeAbonnement = $typeAbonnement;

        return $this;
    }

    public function getRaisonDesabonnement(): ?string
    {
        return $this->raisonDesabonnement;
    }

    public function setRaisonDesabonnement(?string $raisonDesabonnement): self
    {
        $this->raisonDesabonnement = $raisonDesabonnement;

        return $this;
    }
}

src/Entity/Contacts.php
<?php

namespace App\Entity;

use App\Repository\ContactsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactsRepository::class)
 */
class Contacts
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $adressEmail;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $codePostal;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdressEmail(): ?string
    {
        return $this->adressEmail;
    }

    public function setAdressEmail(string $adressEmail): self
    {
        $this->adressEmail = $adressEmail;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(string $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }
}

src/Controller/AdminSubscriptionsListAndFiltersController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Entity\Abonnement;
use App\Form\FormSearchType;
use App\Entity\SubscriptionSearch;
use App\Repository\UserRepository;
use App\Form\SubscriptionSearchType;
use App\Repository\ClientRepository;
use App\Repository\AbonnementRepository;
use App\Repository\SousCompteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @IsGranted("ROLE_ADMIN")
 */
class AdminSubscriptionsListAndFiltersController extends AbstractController
{
    private $userRepository;

    private $clientRepository;

    public function __construct(UserRepository $userRepository, ClientRepository $clientRepository){
        $this->userRepository = $userRepository;
        $this->clientRepository = $clientRepository;
    }

    /**
     * @Route("/admin/subscription/list/and/filters", name="admin_subscription_list_and_filters")
     */
    public function index(Request $request): Response
    {
        $search = new SubscriptionSearch();
        $form = $this->createForm(FormSearchType::class, $search);
        $form->handleRequest($request);

        //$everyClient = $this->clientRepository->findAll();
        $everyClient = $this->clientRepository->findBy([], ['id' => 'DESC']);

        if ($form->isSubmitted() && $form->isValid()){
            $everyClient = $this->clientRepository->findAllClientsResearched($search);
        }

        return $this->render('admin_subscriptions_list_and_filters/index.html.twig', [
            'controller_name' => 'AdminSubscriptionsListAndFiltersController',
            'clients' => $everyClient,
            'form' => $form->createView()
        ]);
    }

    /**
    * @Route("/admin/sous_compte/list/{id}", name="admin_sous_compte_list")
    */
    public function sousCompte( int $id, SousCompteRepository $sousCompteRepository, ClientRepository $clientrepository ): Response
    {
        $conClient=$clientrepository->findOneBy(['id'=>$id]);
        $consous = $conClient->getSouscomptes()->getValues();
        
        return $this->render('admin_subscriptions_list_and_filters/sous_compte.html.twig',[
            'sous_comptes' => $consous
        ]);
    }

    /**
     * @Route("/des", name="des")
     */
    public function listDesabonne(Request $request, EntityManagerInterface $em, AbonnementRepository $Arep ,ClientRepository $clientrepository ): Response
    {
        $unsubscribedClientsSearch = new SubscriptionSearch();
        $form = $this->createForm(SubscriptionSearchType::class, $unsubscribedClientsSearch);
        $form->handleRequest($request);
        
        $conClients = $clientrepository->findAllUnsubscribedUsers();

        if ($form->isSubmitted() && $form->isValid()) {
            //dd($unsubscribedClientsSearch);
            $conClients = $clientrepository->findUnsubscribedClients($unsubscribedClientsSearch);
            //dd($conClients);
        }
        
        return $this->render('admin_subscriptions_list_and_filters/listDesabonne.html.twig', [
            'clients' => $conClients,
            'form' => $form->createView()
        ]);
    }

}

templates/admin_subscriptions_list_and_filters/index.html.twig
{% extends 'mqbaka_home/index.html.twig' %}

{% block title %}Tableau de bord - Admin
{% endblock %}

{% block body %}
    <meta name="viewport" content="widht=device-widht , initial-scale=1.0">
	<link href= {{ asset("/css/admin-dash.css") }} rel="stylesheet">
    <link href={{ asset('css/list.css') }} rel="stylesheet">


        <div class="dash-outliner">
            {% include "admin/admin-header-admin.html.twig" %}
            <div class="dash-container sidebared">
                {% include "admin/components/sidebarAdmin.html.twig" %} 
                <div class="middle-content">
 	                <h2 class="tête" f><img class="image" src={{ asset('images/icon/list-d.svg') }}>Agences info</h2>
                    <div class="table-ext-wrapper" style="display: flex;flex-direction: column;">
                        {% include "admin/components/filterForm.html.twig" %}
                        <div class="table-agences">
                            <table class="agence">
                                <thead>
                                    <tr>
                                        <th>Agence <br>  </th>
                                        <th>Adresse</th>
                                        <th>email</th>
                                        <th>télephone</th>
                                        <th>Type d'abonnement</th>
                                        <th>debut de l'abonnement</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for client in clients %}
                                        <tr>
                                            
                                            <td>
                                                <a id="agence_sous_compte_liste" href="{{ path('admin_sous_compte_list', { id: client.id }) }}">
                                                    {{ client.nomEntreprise }}
                                                </a>
                                            </td>
                                            <td>
                                                {{ client.address }} </br> 
                                                {{ client.postalCode }} - {{ client.town }}  
                                            </td>
                                            <td>
                                                {{ client.email }}<br>
                                            </td>
                                            <td>
                                                {{ client.telMobile }}
                                            </td>
                                            <td>
                                                {{ client.abonnement.typeAbonnement ? client.abonnement.typeAbonnement.label : 'Aucun type d\'abonnement' }}
                                            </td>
                                            <td>
                                                {{ client.abonnement.dateDebutAbonnement|date("d/m/Y") }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
    <div class="mobile-ham" onclick="toggleSideMobile()">
        <div class="ham-line"></div>
        <div class="ham-line"></div>
        <div class="ham-line"></div>
    </div>
    <script title="for the sidebar to show and collapse">

        function toggleSide(){
            let side= document.querySelector(".dash-container");
            side.classList.toggle('sidebared');
        }

        function toggleSideMobile(){
            let side= document.querySelector('.sidebarMenu');
            let ham= document.querySelector('.mobile-ham');

            ham.classList.toggle('expanded');
            side.classList.toggle('expanded');
        }
    </script>

{% endblock %}





{# extends 'base.html.twig' %}

.list-filter{
  background-color: #203c7688;
  padding: 1em;
  width: max;
  border-radius: 5px
}

.champ-filtre{
  height: 2em;
  border: none;
  border-bottom: solid 1px;
  color: white;
}

{% block title %}Hello AdminSubscriptionListAndFiltersController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/PHP/financer_et_moi/src/Controller/AdminSubscriptionListAndFiltersController.php'|file_link(0) }}">src/Controller/AdminSubscriptionListAndFiltersController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/PHP/financer_et_moi/templates/admin_subscription_list_and_filters/index.html.twig'|file_link(0) }}">templates/admin_subscription_list_and_filters/index.html.twig</a></code></li>
    </ul>
</div>

<div>
    {{ form_start(form) }}
        {{ form_row(form.subscription) }}
        {{ form_row(form.town) }}
        {{ form_row(form.postalCode) }}
        <button type="submit">Rechercher</button>
    {{ form_end(form) }}
</div>
{% endblock #}

templates/admin_subscriptions_list_and_filters/listDesabonne.html.twig
{% extends 'mqbaka_home/index.html.twig' %}

{% block title %}Tableau de bord - Admin
{% endblock %}

{% block body %}
    <meta name="viewport" content="widht=device-widht , initial-scale=1.0">
	<link href= {{ asset("/css/admin-dash.css") }} rel="stylesheet">
    <link href={{ asset('css/list.css') }} rel="stylesheet">


        <div class="dash-outliner">
            {% include "admin/admin-header-admin.html.twig" %}
            <div class="dash-container sidebared">
                {% include "admin/components/sidebarAdmin.html.twig" %} 
                <div class="middle-content">
 	                <h2 class="tête" f><img class="image" src={{ asset('images/icon/list-d.svg') }}>Liste des comptes inactifs</h2>
                    <div class="table-ext-wrapper" style="display: flex;flex-direction: column;">
                        {% include "admin/components/filterForm.html.twig" %}
                        <div class="table-agences">
                            <table class="agence">
                                <thead>
                                    <tr>
                                        <th>Agence <br>  </th>
                                        <th>Adresse</th>
                                        {# <th>email</th>
                                        <th>télephone</th> #}
                                        <th>Type d'abonnement</th>
                                        <th>debut de l'abonnement</th>
                                        <th>fin de l'abonnement</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for client in clients %}
                                        <tr>
                                            
                                            <td>
                                                {{ client.nomEntreprise }}   
                                            </td>
                                            <td>
                                                {{ client.address }} </br> 
                                                {{ client.postalCode }} - {{ client.town }}  
                                            </td>
                                            {# <td>
                                                {{ client.email }}<br>
                                            </td>
                                            <td>
                                                {{ client.telMobile }}
                                            </td> #}
                                            <td>
                                                {# desbonne #}
                                                {{ client.abonnement.typeAbonnement ? client.abonnement.typeAbonnement.label : 'Aucun type d\'abonnement' }}
                                            </td>
                                            <td>
                                                {{ client.abonnement.dateDebutAbonnement|date("d/m/Y") }}
                                            </td>
                                            <td>
                                                {% if client.abonnement.dateFinAbonnement %}
                                                    {{ client.abonnement.dateFinAbonnement|date("d/m/Y")}}
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
    <div class="mobile-ham" onclick="toggleSideMobile()">
        <div class="ham-line"></div>
        <div class="ham-line"></div>
        <div class="ham-line"></div>
    </div>
    <script title="for the sidebar to show and collapse">

        function toggleSide(){
            let side= document.querySelector(".dash-container");
            side.classList.toggle('sidebared');
        }

        function toggleSideMobile(){
            let side= document.querySelector('.sidebarMenu');
            let ham= document.querySelector('.mobile-ham');

            ham.classList.toggle('expanded');
            side.classList.toggle('expanded');
        }
    </script>

{% endblock %}

templates/admin_subscriptions_list_and_filters/sous_compte.html.twig
{% extends 'mqbaka_home/index.html.twig' %}

{% block title %}Tableau de bord - Admin
{% endblock %}

{% block body %}
    <meta name="viewport" content="widht=device-widht , initial-scale=1.0">
	<link href= {{ asset("/css/admin-dash.css") }} rel="stylesheet">
    <link href={{ asset('css/list.css') }} rel="stylesheet">


        <div class="dash-outliner">
            {% include "admin/admin-header-admin.html.twig" %}
            <div class="dash-container sidebared">
                {% include "admin/components/sidebarAdmin.html.twig" %} 
                <div class="middle-content">
 	                {# <h2 class="tête" f><img class="image" src={{ asset('images/icon/list-d.svg') }}>Liste des agences</h2> #}
                    <div class="table-ext-wrapper" style="display: flex;flex-direction: column;">
                        
                        <div class="table-agences">
                            <table class="agence">
                                <thead>
                                    <tr>
                                        <th>Nom sous-compte <br>  </th>
                                        <th>Adresse</th>
                                        <th>email</th>
                                        <th>télephone</th>
                                        <th>Type d'abonnement</th>
                                        <th>debut de l'abonnement</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for client in sous_comptes %}
                                        <tr>
                                            
                                            <td>
                                                {{ client.nomEntreprise }}
                                            </td>
                                            <td>
                                                {{ client.addresseEntreprise }} </br> 
                                                {{ client.codePostal }} - {{ client.ville }}  
                                            </td>
                                            <td>
                                                {{ client.email }}<br>
                                            </td>
                                            <td>
                                                {{ client.telMobile }}
                                            </td>
                                            <td>
                                                {{ client.abonnement.typeAbonnement ? client.abonnement.typeAbonnement.label : 'Aucun type d\'abonnement' }}
                                            </td>
                                            <td>
                                                {{ client.abonnement.dateDebutAbonnement|date("m/d/Y") }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
    <div class="mobile-ham" onclick="toggleSideMobile()">
        <div class="ham-line"></div>
        <div class="ham-line"></div>
        <div class="ham-line"></div>
    </div>
    <script title="for the sidebar to show and collapse">

        function toggleSide(){
            let side= document.querySelector(".dash-container");
            side.classList.toggle('sidebared');
        }

        function toggleSideMobile(){
            let side= document.querySelector('.sidebarMenu');
            let ham= document.querySelector('.mobile-ham');

            ham.classList.toggle('expanded');
            side.classList.toggle('expanded');
        }
    </script>

{% endblock %}